### ISSUE TITLE
Docusing Error while requesting server, received a non successful HTTP code Completed with response Body: {"error":"consent_required"}

### ISSUE THREAD

**Issue by UrvishPatel92** [docusign/code-examples-csharp#24]
I got this error while request JWT token. 

Step: 1
so i request to 
"https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id={clinet_id}&redirect_uri=https://localhost:44333/ds/login?authType=JWT#/username"

Step:2
Redirect To me on authorized page
[![enter image description here][1]][1]

Step: 3
Afte Accept redirect on login page and again try to Authorzation with JWT token but still getting same error as above.

[![enter image description here][2]][2]

setting on docusign as per below i gave Permissions for "signature impersonation" in my docusign account. 

[![enter image description here][3]][3]
[![enter image description here][4]][4]

can you please help me what i wrong in it. i check another linked also "https://stackoverflow.com/questions/63713136/docusign-error-while-requesting-server-received-a-non-successful-http-code-comp" but i already include the impersonation scope but don't know why always getting same error. 

  [1]: https://i.stack.imgur.com/0bY8v.png
  [2]: https://i.stack.imgur.com/MaTnk.png
  [3]: https://i.stack.imgur.com/Whh3v.png
  [4]: https://i.stack.imgur.com/F6xqn.png

**Comment by InbarGazit** [comment]
This was fixed. I also noted I need to add https://localhost:44333/ds/login?authType=JWT to the list of redirectURIs for quickstart, but you seem to already have figured this out.

**Comment by UrvishPatel92** [comment]
Thank you for quick answer Inbar Gazit. now it working
