### ISSUE TITLE
Minor refactoring suggestion

### ISSUE THREAD

**Issue by dean-kukol-cms** [docusign/code-examples-csharp#25]
This is such a wonderful job and great resource for someone new to DocuSign.  We really appreciate it!!

May I offer one small refactoring suggestion, please?  Could the prefixes of the 2 properties in bold be modified to 'SignerEmail' and 'SignerName' in light of the naming convention used for the class name of 'EmbeddedSigningModel'...  Thank you!

namespace DocuSign.CodeExamples.Views
{
    public class Embedded**Signing**Model
    {
        public string **SingerEmail**  { get; set; }
        public string **SingerName** { get; set; }
    }
}

**Comment by dmartin00** [comment]
Thanks for the feedback. I've filed this request with our Developer Content team for review. For reference, the internal issue number for this is DCM-5228.
