### ISSUE TITLE
500  Error while creating JWT Token 

### ISSUE THREAD

**Issue by tpbadgujar** [docusign/code-examples-csharp#30]
Hello Team,

We are Requesting JWT token using RequestJWTUserToken() method along with the valid (required) parameters. but we could see that sometimes it is working fine and sometimes not.

We are getting below error with no response body.

`Error while requesting server, received a non successful HTTP code with response Body:  :    at DocuSign.eSign.Client.DocuSignClient.RequestJWTUserToken(String clientId, String userId, String oauthBasePath, Byte[] privateKeyBytes, Int32 expiresInHours, List`1 scopes)`

We have given the scope as "signature impersonation" for the DocuSign Demo Account.

Please let us know.

**Comment by InbarGazit** [comment]
Any idea what makes it work or not? like is it just completely random? do you run this code from a server? is it behind some firewall? do you run it exactly the same way, with the same configuration and sometimes it works?

**Comment by tpbadgujar** [comment]
`Any idea what makes it work or not?` - We could not able to find. It is randomly working and randomly not working.

`do you run this code from a server? is it behind some firewall?` - Yes, we are running the code from the server and we have whitelisted this URL's in our firewall.

`do you run it exactly the same way, with the same configuration and sometimes it works?` - Yes, without doing any code or configuration change, sometimes it is working and sometime not.

**Comment by InbarGazit** [comment]
There has to be some difference, between the working calls and the one giving errors. This is a result of a configuration issue. May need to add additional logging to your app and log all the information you pass to this method and compare good calls to bad calls.

**Comment by InbarGazit** [comment]
Can you use fiddler or some other networking tool to capture logs when this fails?

**Comment by InbarGazit** [comment]
Hello @tpbadgujar  , do you still need help with this issue?
