### ISSUE TITLE
RuntimeBinderException with Quick_ACG project

### ISSUE THREAD

**Issue by MatthewCarse** [docusign/code-examples-csharp#36]
RuntimeBinderException: 'DocuSign.CodeExamples.ESignature.Models.CodeExampleText' does not contain a definition for 'LinksToAPIMethod'

Error when running solution due to property names accessed through ViewBag (Api vs API)

**Comment by InbarGazit** [comment]
Looking into this, will have an answer shortly

**Comment by InbarGazit** [comment]
Fixed, please confirm and then close

**Comment by MatthewCarse** [comment]
I had already added a PR for it, but you have made the same changes so I will close it.
